### ISSUE TITLE
[RK3399] Warning: SPL image is too large (size 0x63000) and will not boot

### ISSUE THREAD

**Issue by dmikushin** [amarula/u-boot-amarula#1]
Hi, I've followed the [guide](https://wiki.amarulasolutions.com/bsp/rockchip/rk3399/nanopi_m4.html) and checked RK3399 U-boot offered in the `master` branch here. Unfortunately, the process fails here:

```
/tools/mkimage -n rk3399 -T rksd -d ./spl/u-boot-spl-dtb.bin щге
Warning: SPL image is too large (size 0x63000) and will not boot
Error: image verification failed
```

Could you please kindly let me know which commit was successful for you at the time the guide was written? Thank you!

**Comment by panicking** [comment]
git clone https://gitlab.denx.de/u-boot/u-boot.git

Use the mainline uboot. I have compiled right now. We need to update the documentation. Anyway if you have a successful boot you can create a pull request on the wiki and we can merge

https://github.com/amarula/wiki-amarula/

**Comment by dmikushin** [comment]
Hi, yes, there is no such problem when building mainline uboot. However, I cannot boot to anything. No signal from HDMI, no UART TTL (I'm trying CP2102, for me it's very hard to say whether it supports 1500000 baud rate or not). Could you please kindly advice on booting directions?

**Comment by openedev** [comment]
Hi, thanks for noticing.

Please use this repo https://github.com/amarula/u-boot-amarula/tree/rockchip
$ make nanopi-m4-rk3399_defconfig
$ make 
$ sudo dd if=u-boot-rockchip.bin of=/dev/mmcblk0 seek=64

(with this you can even seen the HDMI out working).

We are using pl2303 serial with 1500000 baudrate
Bus 003 Device 004: ID 067b:2303 Prolific Technology, Inc. PL2303 Serial Port

I will update the wiki soon.

**Comment by openedev** [comment]
@dmikushin please check the wiki, we have updated.

https://wiki.amarulasolutions.com/bsp/rockchip/rk3399/nanopi_m4.html

**Comment by openedev** [comment]
Issues fixed!
